package ensemblecare.csardent.com.preference

class PrefKeys {
    companion object {
        const val PREF_IS_LOGGEDIN = "is_logged_in"
        const val PREF_IS_CARE_BUDDY_LOGGEDIN = "is_care_buddy_logged_in"
        const val PREF_IS_COMPANION_LOGGEDIN = "is_companion_logged_in"
        const val PREF_IS_REMEMBER_ME = "is_remember_me"
        const val PREF_CARE_BUDDY_IS_REMEMBER_ME = "care_buddy_is_remember_me"
        const val PREF_STEP = "step"            //Int
        const val PREF_ID = "id"                //Int
        const val PREF_DEVICE_ID = "device_id"  //String
        const val PREF_SELECTED_THERAPY = "selected_therapy"  //String
        const val PREF_USER_ID = "user_id"
        const val PREF_EMAIL = "email"
        const val PREF_PHONE_NO = "phone_no"
        const val PREF_FNAME = "fname"
        const val PREF_MNAME = "mname"
        const val PREF_LNAME = "lname"
        const val PREF_DOB = "dob"
        const val PREF_ETHNICITY = "ethnicity"
        const val PREF_ROLE = "role"
        const val PREF_SSN = "ssn"
        const val PREF_GENDER = "gender"
        const val PREF_ADDRESS = "address"
        const val PREF_ADDRESS1 = "address1"
        const val PREF_COUNTRY = "country"
        const val PREF_STATE = "state"
        const val PREF_CITY = "city"
        const val PREF_ZIPCODE = "zipcode"
        const val PREF_PREFERRED_LANG = "preferred_language"
        const val PREF_RELATIONSHIP = "relationship"
        const val PREF_MARTIAL_STATUS = "martial_status"
        const val PREF_EMERGENCY_CONTACT_NAME = "emergency_contact_name"
        const val PREF_PATIENT_ID = "patient_id"
        const val PREF_SELECTED_PLAN = "selected_plan"
        const val PREF_SEVERITY_SCORE = "severity_score"
        const val PREF_SELECTED_SERVICE = "selected_service"
        const val PREF_SELECTED_DISORDER = "selected_disorder"
        const val PREF_PHOTO = "user_photo"
        const val PREF_PASS = "pass"
        const val PREF_REG = "register"
        const val PREF_CARE_BUDDY_EMAIL = "care_buddy_email"
        const val PREF_CARE_BUDDY_PASS = "care_buddy_pass"
        const val PREF_REFRESH_TOKEN = "refresh_token"
        const val PREF_ACCESS_TOKEN = "access_token"
        const val PREF_Journal_Added = "journalAdded"
        const val PREF_Personal_Goal_Added = "personalGoalAdded"
        const val PREF_NEXT_QUESTION_ID = "next_question_id"
        const val PREF_SET_ANSWER = "set_answer"
        const val PREF_INSURANCE_VERIFICATION = "insurance_verified"
        const val PREF_IS_COLUMBIA_SEVERITY = "is_columbia_severity"
        const val PREF_NOTIFY_ID = "notify_id"
        const val PREF_INTEREST_SELECTED = "interest_selected"
        const val PREF_FCM_TOKEN = "fcm_token"
    }
}